apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: iu8azax9z-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: iu8azax9z-python 
  name: iu8azax9z-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: iu8azax9z-python 
